# Health Inequality Project 

This is looking at health inequality within the UK. 

In this project health inequality is based on life expectancy, rates of mortality regarding diseases, diagnostic waiting times, etc. This expectancy varies by Area, Demographic, Deprivation and Education

The first section of code is looking at life expectancy, the second diagnostic waiting times

The data for life expectancy is looking between 2021 - 2023

In [1]:
%load_ext sql
%config SqlMagic.style = 'PLAIN_COLUMNS'   # or 'MARKDOWN'
%config SqlMagic.autopandas = True         # return pandas DataFrames

In [2]:
import pandas as pd
import sqlite3

df= pd.read_csv("/Users/lulum/Documents/Coding Projects/01 PRJ  - UK Health Inequality/datasets/lifeexpectancylocalareas_period_2001_to_2023.csv")
df.head()

conn = sqlite3.connect("life_expectancyy.db")
df.to_sql("life_expectancyy", conn, index=False, if_exists="replace")

df

,Period,Country,Area type,Area code,Area name,Sex,Sex code,Age band,Age group,Life expectancy,Lower confidence interval,Upper confidence interval
0,2001 to 2003,England,Local Areas,E06000001,Hartlepool,Male,1,1,<1,73.42,72.68,74.16
1,2001 to 2003,England,Local Areas,E06000001,Hartlepool,Male,1,2,01 to 04,72.90,72.21,73.58
2,2001 to 2003,England,Local Areas,E06000001,Hartlepool,Male,1,3,05 to 09,68.94,68.26,69.61
3,2001 to 2003,England,Local Areas,E06000001,Hartlepool,Male,1,4,10 to 14,63.97,63.30,64.65
4,2001 to 2003,England,Local Areas,E06000001,Hartlepool,Male,1,5,15 to 19,59.00,58.33,59.67
...,...,...,...,...,...,...,...,...,...,...,...,...
335155,2021 to 2023,Wales,Country,W92000004,Wales,Female,2,16,70 to 74,16.47,16.40,16.54
335156,2021 to 2023,Wales,Country,W92000004,Wales,Female,2,17,75 to 79,12.76,12.69,12.82
335157,2021 to 2023,Wales,Country,W92000004,Wales,Female,2,18,80 to 84,9.41,9.34,9.47
335158,2021 to 2023,Wales,Country,W92000004,Wales,Female,2,19,85 to 89,6.66,6.60,6.72
335159,2021 to 2023,Wales,Country,W92000004,Wales,Female,2,20,90+,4.48,4.41,4.56

In [3]:
%load_ext sql
%sql sqlite:///life_expectancyy.db

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [5]:

query = """
SELECT 
    Period,
    substr(Period, 1, 4) AS start_year,
    substr(Period, 9, 12)AS end_year
FROM life_expectancyy;
 """
result_df = pd.read_sql(query, conn)


result_df

              Period start_year end_year
0       2001 to 2003       2001     2003
1       2001 to 2003       2001     2003
2       2001 to 2003       2001     2003
3       2001 to 2003       2001     2003
4       2001 to 2003       2001     2003
...              ...        ...      ...
335155  2021 to 2023       2021     2023
335156  2021 to 2023       2021     2023
335157  2021 to 2023       2021     2023
335158  2021 to 2023       2021     2023
335159  2021 to 2023       2021     2023

[335160 rows x 3 columns]

In [6]:
query = """
SELECT 
    *
FROM 
    life_expectancyy
 """
result_df = pd.read_sql(query, conn)


result_df

,Period,Country,Area type,Area code,Area name,Sex,Sex code,Age band,Age group,Life expectancy,Lower confidence interval,Upper confidence interval
0,2001 to 2003,England,Local Areas,E06000001,Hartlepool,Male,1,1,<1,73.42,72.68,74.16
1,2001 to 2003,England,Local Areas,E06000001,Hartlepool,Male,1,2,01 to 04,72.90,72.21,73.58
2,2001 to 2003,England,Local Areas,E06000001,Hartlepool,Male,1,3,05 to 09,68.94,68.26,69.61
3,2001 to 2003,England,Local Areas,E06000001,Hartlepool,Male,1,4,10 to 14,63.97,63.30,64.65
4,2001 to 2003,England,Local Areas,E06000001,Hartlepool,Male,1,5,15 to 19,59.00,58.33,59.67
...,...,...,...,...,...,...,...,...,...,...,...,...
335155,2021 to 2023,Wales,Country,W92000004,Wales,Female,2,16,70 to 74,16.47,16.40,16.54
335156,2021 to 2023,Wales,Country,W92000004,Wales,Female,2,17,75 to 79,12.76,12.69,12.82
335157,2021 to 2023,Wales,Country,W92000004,Wales,Female,2,18,80 to 84,9.41,9.34,9.47
335158,2021 to 2023,Wales,Country,W92000004,Wales,Female,2,19,85 to 89,6.66,6.60,6.72
335159,2021 to 2023,Wales,Country,W92000004,Wales,Female,2,20,90+,4.48,4.41,4.56

In [7]:

query = """
DROP VIEW IF EXISTS life_expect;

CREATE VIEW life_expect 
AS
SELECT 
    Period as period,
    substr(Period, 1, 4) AS start_year,
    substr(Period, 9, 12)AS end_year,
    Country as country,
    `Area type` as area_types,
    `Area code` as area_code,
    `Area name` as area_name,
     Sex as sex,
    `Sex code` as sex_code,
    `Age band` as age_band,
    `Age group` as age_group,
    `Life expectancy` as life_expectancy,
    `Lower confidence interval` as lower_confidence_interval,
    `Upper confidence interval` as upper_confidence_interval
FROM 
    life_expectancyy
WHERE 
    start_year = '2021' 
    AND end_year = '2023'
    AND `Area type` = 'Local Areas'
    AND Country = 'England' ;
"""

conn.executescript(query)  
conn.commit()

query = """
SELECT 
    *
FROM 
    life_expect
 """
 
result_df = pd.read_sql(query, conn)
result_df

,period,start_year,end_year,country,area_types,area_code,area_name,sex,sex_code,age_band,age_group,life_expectancy,lower_confidence_interval,upper_confidence_interval
0,2021 to 2023,2021,2023,England,Local Areas,E06000001,Hartlepool,Male,1,1,<1,76.66,75.87,77.45
1,2021 to 2023,2021,2023,England,Local Areas,E06000001,Hartlepool,Male,1,2,01 to 04,76.14,75.42,76.87
2,2021 to 2023,2021,2023,England,Local Areas,E06000001,Hartlepool,Male,1,3,05 to 09,72.14,71.42,72.87
3,2021 to 2023,2021,2023,England,Local Areas,E06000001,Hartlepool,Male,1,4,10 to 14,67.14,66.42,67.87
4,2021 to 2023,2021,2023,England,Local Areas,E06000001,Hartlepool,Male,1,5,15 to 19,62.21,61.49,62.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11755,2021 to 2023,2021,2023,England,Local Areas,E09000033,Westminster,Female,2,16,70 to 74,18.86,18.41,19.30
11756,2021 to 2023,2021,2023,England,Local Areas,E09000033,Westminster,Female,2,17,75 to 79,14.92,14.49,15.36
11757,2021 to 2023,2021,2023,England,Local Areas,E09000033,Westminster,Female,2,18,80 to 84,11.46,11.03,11.89
11758,2021 to 2023,2021,2023,England,Local Areas,E09000033,Westminster,Female,2,19,85 to 89,8.12,7.68,8.57
11759,2021 to 2023,2021,2023,England,Local Areas,E09000033,Westminster,Female,2,20,90+,5.46,4.94,5.99

In [8]:
query = """
SELECT 
    *,
    COUNT(age_band) as count_age_band

FROM 
    life_expect
WHERE
     sex = 'Male'

 """
 
result_df = pd.read_sql(query, conn)


result_df

,period,start_year,end_year,country,area_types,area_code,area_name,sex,sex_code,age_band,age_group,life_expectancy,lower_confidence_interval,upper_confidence_interval,count_age_band
0,2021 to 2023,2021,2023,England,Local Areas,E06000001,Hartlepool,Male,1,1,<1,76.66,75.87,77.45,5880

In [9]:
query = """
SELECT 
    area_code,
    area_name, 
    SUM(life_expectancy) as sum_life,
    (SUM(life_expectancy)/20) as avg_life_expect
FROM 
    life_expect
WHERE 
    sex = 'Male'
GROUP BY 
    area_name
ORDER BY 
    avg_life_expect DESC
 """
 
result_df = pd.read_sql(query, conn)


result_df

     area_code                    area_name  sum_life  avg_life_expect
0    E07000089                         Hart    859.21          42.9605
1    E07000077                   Uttlesford    847.82          42.3910
2    E07000012         South Cambridgeshire    845.98          42.2990
3    E09000027         Richmond upon Thames    843.86          42.1930
4    E06000041                    Wokingham    843.29          42.1645
..         ...                          ...       ...              ...
289  E06000008        Blackburn with Darwen    746.44          37.3220
290  E07000117                      Burnley    745.53          37.2765
291  E06000010  Kingston upon Hull, City of    741.95          37.0975
292  E08000003                   Manchester    739.67          36.9835
293  E06000009                    Blackpool    719.24          35.9620

[294 rows x 4 columns]

# Number of GP Surgeries in local authroity districs

In [10]:
df= pd.read_csv("/Users/lulum/Documents/Coding Projects/01 PRJ  - UK Health Inequality/datasets/numofgpsurgeries_eng_and_wales_ 2024.csv")
df.head()

conn = sqlite3.connect("num_gp_surgeries.db")
df.to_sql("num_gp_surgeries", conn, index=False, if_exists="replace")

df

,LAD code,LAD name,Rural Urban Classification (Note 1),Count (Note 3),"GPs per 100,000 people"
0,E06000001,Hartlepool,Urban with City and Town,16,16.78
1,E06000002,Middlesbrough,Urban with City and Town,22,14.41
2,E06000003,Redcar and Cleveland,Urban with Significant Rural,18,13.05
3,E06000004,Stockton-on-Tees,Urban with City and Town,23,11.36
4,E06000005,Darlington,Urban with City and Town,12,10.85
...,...,...,...,...,...
313,W06000020,Torfaen,Wales,11,11.77
314,W06000021,Monmouthshire,Wales,11,11.63
315,W06000022,Newport,Wales,16,9.78
316,W06000023,Powys,Wales,17,12.65
317,W06000024,Merthyr Tydfil,Wales,7,11.95

In [11]:

query = """
DROP VIEW IF EXISTS num_gpsurgeries;

CREATE VIEW num_gpsurgeries 
AS
SELECT 
    `LAD code` AS lad_code,
    `LAD name` AS lad_name,
    `Rural Urban Classification (Note 1)` AS rural_urban_classification,
    `Count (Note 3)` AS count,
    `GPs per 100,000 people` AS gp_per_hundreadthousand 
FROM 
    num_gp_surgeries ;
"""

conn.executescript(query)  
conn.commit()

query = """
SELECT 
    *
FROM 
    num_gpsurgeries
 """
 
result_df = pd.read_sql(query, conn)
result_df

,lad_code,lad_name,rural_urban_classification,count,gp_per_hundreadthousand
0,E06000001,Hartlepool,Urban with City and Town,16,16.78
1,E06000002,Middlesbrough,Urban with City and Town,22,14.41
2,E06000003,Redcar and Cleveland,Urban with Significant Rural,18,13.05
3,E06000004,Stockton-on-Tees,Urban with City and Town,23,11.36
4,E06000005,Darlington,Urban with City and Town,12,10.85
...,...,...,...,...,...
313,W06000020,Torfaen,Wales,11,11.77
314,W06000021,Monmouthshire,Wales,11,11.63
315,W06000022,Newport,Wales,16,9.78
316,W06000023,Powys,Wales,17,12.65
317,W06000024,Merthyr Tydfil,Wales,7,11.95

# Number of